name: "Terraform Deployment"
on:
  workflow_dispatch:
jobs:
  terraform:
        name: VPC peering
        runs-on: ubuntu-latest
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        steps:
            - name: Checkout the code
              uses: actions/checkout@v2

            - name: set the terraform environment
              uses: hashicorp/setup-terraform@v1
              with:
                terraform_wrapper: false

            - name: Terraform Init - Initialization of terraform
              id: init
              run: terraform init
            
            - name: Terraform Validate -  Validation of credentials
              id: validate
              run: terraform validate

            - name: Terraform Plan - Validation of the changes
              id: plan
              run: terraform plan
              continue-on-error: true
            - name: Terraform Plan Status - run if terraform plan is failed
              if: steps.plan.outcome == 'success'
              run: |
                echo "You terraform plan is success"

            - name: Terraform Plan Status - run if terraform plan is failed
              if: steps.plan.outcome == 'failure'
              run: exit 1




















